name: tadamon_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- الأيقونات والرسومات ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10

  # --- إدارة الحالة (State Management) ---
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # --- البرمجة الوظيفية (Clean Arch Core) ---
  dartz: ^0.10.1

  # --- حقن التبعيات (Dependency Injection) ---
  get_it: ^8.0.3

  # --- التجاوب مع الشاشات (Responsive UI) ---
  flutter_screenutil: ^5.9.3

  # --- الاتصال بالسيرفر (Networking) ---
  dio: ^5.8.0+1

  # --- التعامل مع الصور ---
  cached_network_image: ^3.4.1

  # --- التخزين المحلي (Local Storage) ---
  shared_preferences: ^2.3.2

  # --- رسائل التنبيه (Toasts) - (جديد ومهم للمتاجر) ---
  fluttertoast: ^8.2.10
  share_plus: ^10.1.0

  # --- الترجمة واللغات (Localization) ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  
  # مكتبات اللغات اللي إحنا محتاجينها
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



# --- إعدادات فلاتر ---
flutter:
  uses-material-design: true

  # --- تفعيل المجلدات ---
  assets:
    - assets/images/
    
    - assets/fonts/

  # --- إعداد الخط العربي (Cairo) ---
  # ملاحظة: لازم تنزل ملف الخط وتحطه في assets/fonts/Cairo-Regular.ttf
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
